-- Ingredient Dictionary v0.2 seed
-- Public knowledge-base data only. Safe to re-run after 006_content_v0_2.sql.

insert into public.ingredients (
  ingredient_key,
  zh_name,
  en_name,
  category_key,
  aliases,
  default_unit_key,
  is_fresh,
  is_pantry_item,
  is_active,
  sort_order,
  content_tier,
  subcategory_key,
  storage_type,
  is_basic_pantry,
  is_fridge_recognition_target
)
values
  ('rice', '大米', 'Rice', 'grain', array['大米', '米', '白米', '生米', 'rice', 'white rice', 'uncooked rice']::text[], 'cup', false, true, true, 1010, 'P0', 'staple_carbs', 'pantry', false, false),
  ('noodles', '面条', 'Noodles', 'grain', array['面条', '挂面', '面', 'noodles', 'asian noodles', 'wheat noodles']::text[], 'serving', false, true, true, 1020, 'P0', 'staple_carbs', 'pantry', false, false),
  ('pasta', '意大利面', 'Pasta', 'grain', array['意大利面', '意面', '通心粉', 'pasta', 'spaghetti', 'penne']::text[], 'serving', false, true, true, 1030, 'P0', 'staple_carbs', 'pantry', false, false),
  ('bread', '面包', 'Bread', 'grain', array['面包', '吐司', '切片面包', 'bread', 'toast', 'sandwich bread']::text[], 'piece', true, false, true, 1040, 'P0', 'staple_carbs', 'room_temp', false, true),
  ('potato', '土豆', 'Potato', 'grain', array['土豆', '马铃薯', '洋芋', 'potato', 'potatoes', 'russet potato']::text[], 'piece', true, false, true, 1050, 'P0', 'staple_carbs', 'room_temp', false, true),
  ('sweet_potato', '红薯', 'Sweet Potato', 'grain', array['红薯', '地瓜', 'sweet potato']::text[], 'piece', true, false, true, 1060, 'P0', 'staple_carbs', 'room_temp', false, true),
  ('flour', '面粉', 'Flour', 'grain', array['面粉', '中筋面粉', 'flour', 'all purpose flour']::text[], 'cup', false, true, true, 1070, 'P0', 'staple_carbs', 'pantry', false, false),
  ('tortilla', '玉米饼', 'Tortilla', 'grain', array['玉米饼', '卷饼皮', 'tortilla']::text[], 'piece', false, true, true, 1080, 'P1', 'staple_carbs', 'pantry', false, true),
  ('oats', '燕麦', 'Oats', 'grain', array['燕麦', '燕麦片', 'oats', 'rolled oats']::text[], 'cup', false, true, true, 1090, 'P1', 'staple_carbs', 'pantry', false, false),
  ('ramen_noodles', '拉面', 'Ramen Noodles', 'grain', array['拉面', '日式拉面', 'ramen', 'ramen noodles']::text[], 'serving', false, true, true, 1100, 'P1', 'staple_carbs', 'pantry', false, false),
  ('udon_noodles', '乌冬面', 'Udon Noodles', 'grain', array['乌冬面', '乌冬', 'udon', 'udon noodles']::text[], 'serving', true, false, true, 1110, 'P1', 'staple_carbs', 'fridge', false, true),

  ('egg', '鸡蛋', 'Egg', 'protein', array['鸡蛋', '蛋', '鸡蛋儿', 'egg', 'eggs', 'large eggs']::text[], 'piece', true, false, true, 2010, 'P0', 'egg_soy', 'fridge', false, true),
  ('tofu', '豆腐', 'Tofu', 'protein', array['豆腐', '嫩豆腐', '老豆腐', '北豆腐', 'tofu', 'firm tofu', 'soft tofu']::text[], 'gram', true, false, true, 2020, 'P0', 'egg_soy', 'fridge', false, true),
  ('chicken_breast', '鸡胸肉', 'Chicken Breast', 'protein', array['鸡胸肉', '鸡胸', '鸡脯肉', 'chicken breast', 'chicken breasts', 'boneless chicken breast']::text[], 'gram', true, false, true, 2030, 'P0', 'poultry', 'fridge', false, true),
  ('chicken_thigh', '鸡腿肉', 'Chicken Thigh', 'protein', array['鸡腿肉', '去骨鸡腿肉', '鸡大腿肉', 'chicken thigh', 'chicken thighs', 'boneless chicken thigh']::text[], 'gram', true, false, true, 2040, 'P0', 'poultry', 'fridge', false, true),
  ('ground_beef', '牛肉碎', 'Ground Beef', 'protein', array['牛肉碎', '牛肉馅', '牛绞肉', 'ground beef', 'minced beef', 'beef mince']::text[], 'gram', true, false, true, 2050, 'P0', 'beef', 'fridge', false, true),
  ('pork_slice', '猪肉片', 'Pork Slice', 'protein', array['猪肉片', '猪肉薄片', '肉片', 'pork slice', 'sliced pork', 'thin sliced pork']::text[], 'gram', true, false, true, 2060, 'P0', 'pork', 'fridge', false, true),
  ('ground_pork', '猪肉馅', 'Ground Pork', 'protein', array['猪肉馅', '猪绞肉', 'ground pork']::text[], 'gram', true, false, true, 2070, 'P0', 'pork', 'fridge', false, true),
  ('white_fish', '白鱼', 'White Fish', 'seafood', array['白鱼', '白身鱼', 'white fish']::text[], 'gram', true, false, true, 2080, 'P0', 'fish', 'fridge', false, true),
  ('shrimp', '虾', 'Shrimp', 'seafood', array['虾', '虾仁', '鲜虾', 'shrimp', 'shrimps', 'prawn', 'prawns']::text[], 'gram', true, false, true, 2090, 'P0', 'shellfish', 'fridge', false, true),
  ('canned_tuna', '罐头金枪鱼', 'Canned Tuna', 'seafood', array['罐头金枪鱼', '金枪鱼罐头', '吞拿鱼罐头', 'canned tuna', 'tuna can', 'tinned tuna']::text[], 'gram', false, true, true, 2100, 'P0', 'canned_protein', 'canned', false, false),
  ('chicken_wings', '鸡翅', 'Chicken Wings', 'protein', array['鸡翅', '鸡翅中', 'chicken wings']::text[], 'gram', true, false, true, 2110, 'P1', 'poultry', 'fridge', false, true),
  ('chicken_drumstick', '鸡腿', 'Chicken Drumstick', 'protein', array['鸡腿', '鸡腿肉块', 'chicken drumstick', 'drumstick']::text[], 'piece', true, false, true, 2120, 'P1', 'poultry', 'fridge', false, true),
  ('beef_slice', '牛肉片', 'Beef Slice', 'protein', array['牛肉片', '肥牛片', 'beef slice', 'sliced beef']::text[], 'gram', true, false, true, 2130, 'P1', 'beef', 'fridge', false, true),
  ('beef_shank', '牛腱', 'Beef Shank', 'protein', array['牛腱', '牛腱子', 'beef shank']::text[], 'gram', true, false, true, 2140, 'P1', 'beef', 'fridge', false, true),
  ('ground_turkey', '火鸡碎', 'Ground Turkey', 'protein', array['火鸡碎', '火鸡肉馅', 'ground turkey']::text[], 'gram', true, false, true, 2150, 'P1', 'poultry', 'fridge', false, true),
  ('turkey_breast', '火鸡胸', 'Turkey Breast', 'protein', array['火鸡胸', '火鸡胸肉', 'turkey breast']::text[], 'gram', true, false, true, 2160, 'P1', 'poultry', 'fridge', false, true),
  ('pork_belly', '五花肉', 'Pork Belly', 'protein', array['五花肉', 'pork belly']::text[], 'gram', true, false, true, 2170, 'P1', 'pork', 'fridge', false, true),
  ('bacon', '培根', 'Bacon', 'protein', array['培根', 'bacon']::text[], 'gram', true, false, true, 2180, 'P1', 'pork', 'fridge', false, true),
  ('sausage', '香肠', 'Sausage', 'protein', array['香肠', '腊肠', 'sausage']::text[], 'piece', true, false, true, 2190, 'P1', 'processed_meat', 'fridge', false, true),
  ('pork_chop', '猪排', 'Pork Chop', 'protein', array['猪排', '猪扒', 'pork chop']::text[], 'piece', true, false, true, 2200, 'P1', 'pork', 'fridge', false, true),
  ('salmon', '三文鱼', 'Salmon', 'seafood', array['三文鱼', '鲑鱼', 'salmon']::text[], 'gram', true, false, true, 2210, 'P1', 'fish', 'fridge', false, true),
  ('cod', '鳕鱼', 'Cod', 'seafood', array['鳕鱼', '鳕鱼块', 'cod']::text[], 'gram', true, false, true, 2220, 'P1', 'fish', 'fridge', false, true),
  ('scallops', '扇贝', 'Scallops', 'seafood', array['扇贝', '干贝', 'scallops']::text[], 'gram', true, false, true, 2230, 'P1', 'shellfish', 'fridge', false, true),
  ('imitation_crab', '蟹肉棒', 'Imitation Crab', 'seafood', array['蟹肉棒', '蟹柳', 'imitation crab', 'crab stick']::text[], 'gram', true, false, true, 2240, 'P1', 'seafood_processed', 'fridge', false, true),
  ('duck_breast', '鸭胸', 'Duck Breast', 'protein', array['鸭胸', '鸭胸肉', 'duck breast']::text[], 'gram', true, false, true, 2250, 'P2', 'duck_lamb', 'fridge', false, true),
  ('duck_leg', '鸭腿', 'Duck Leg', 'protein', array['鸭腿', 'duck leg']::text[], 'piece', true, false, true, 2260, 'P2', 'duck_lamb', 'fridge', false, true),
  ('lamb_slice', '羊肉片', 'Lamb Slice', 'protein', array['羊肉片', '涮羊肉', 'lamb slice', 'sliced lamb']::text[], 'gram', true, false, true, 2270, 'P2', 'duck_lamb', 'fridge', false, true),
  ('whelk', '海螺', 'Whelk', 'seafood', array['海螺', '螺肉', 'whelk']::text[], 'gram', true, false, true, 2280, 'P2', 'shellfish', 'fridge', false, true),

  ('onion', '洋葱', 'Onion', 'vegetable', array['洋葱', '黄洋葱', '洋葱头', 'onion', 'onions', 'yellow onion']::text[], 'piece', true, false, true, 3010, 'P0', 'aromatics', 'room_temp', false, true),
  ('red_onion', '红洋葱', 'Red Onion', 'vegetable', array['红洋葱', '紫洋葱', 'red onion']::text[], 'piece', true, false, true, 3020, 'P0', 'aromatics', 'room_temp', false, true),
  ('garlic', '大蒜', 'Garlic', 'vegetable', array['大蒜', '蒜', '蒜瓣', '蒜头', 'garlic', 'garlic cloves', 'garlic clove']::text[], 'piece', true, false, true, 3030, 'P0', 'aromatics', 'room_temp', false, true),
  ('ginger', '姜', 'Ginger', 'vegetable', array['姜', '生姜', '老姜', 'ginger', 'fresh ginger', 'ginger root']::text[], 'gram', true, false, true, 3040, 'P0', 'aromatics', 'fridge', false, true),
  ('scallion', '小葱', 'Scallion', 'vegetable', array['小葱', '葱', '青葱', '葱花', 'scallion', 'scallions', 'green onion', 'spring onion']::text[], 'piece', true, false, true, 3050, 'P0', 'aromatics', 'fridge', false, true),
  ('tomato', '番茄', 'Tomato', 'vegetable', array['番茄', '西红柿', 'tomato', 'tomatoes', 'roma tomato', 'fresh tomato']::text[], 'piece', true, false, true, 3060, 'P0', 'fruiting_vegetable', 'room_temp', false, true),
  ('carrot', '胡萝卜', 'Carrot', 'vegetable', array['胡萝卜', '红萝卜', 'carrot', 'carrots', 'baby carrots']::text[], 'piece', true, false, true, 3070, 'P0', 'root_vegetable', 'fridge', false, true),
  ('cucumber', '黄瓜', 'Cucumber', 'vegetable', array['黄瓜', '青瓜', 'cucumber', 'cucumbers', 'english cucumber']::text[], 'piece', true, false, true, 3080, 'P0', 'fruiting_vegetable', 'fridge', false, true),
  ('lettuce', '生菜', 'Lettuce', 'vegetable', array['生菜', '莴苣叶', 'lettuce', 'romaine', 'romaine lettuce', 'green leaf lettuce']::text[], 'gram', true, false, true, 3090, 'P0', 'leafy_green', 'fridge', false, true),
  ('spinach', '菠菜', 'Spinach', 'vegetable', array['菠菜', 'spinach', 'baby spinach', 'fresh spinach']::text[], 'gram', true, false, true, 3100, 'P0', 'leafy_green', 'fridge', false, true),
  ('cabbage', '卷心菜', 'Cabbage', 'vegetable', array['卷心菜', '包菜', '圆白菜', 'cabbage', 'green cabbage', 'head cabbage']::text[], 'gram', true, false, true, 3110, 'P0', 'cruciferous', 'fridge', false, true),
  ('broccoli', '西兰花', 'Broccoli', 'vegetable', array['西兰花', '西蓝花', 'broccoli', 'broccoli florets', 'fresh broccoli']::text[], 'gram', true, false, true, 3120, 'P0', 'cruciferous', 'fridge', false, true),
  ('cauliflower', '花椰菜', 'Cauliflower', 'vegetable', array['花椰菜', '菜花', '白花菜', 'cauliflower', 'cauliflower florets']::text[], 'gram', true, false, true, 3130, 'P0', 'cruciferous', 'fridge', false, true),
  ('mushroom', '蘑菇', 'Mushroom', 'vegetable', array['蘑菇', '鲜蘑菇', '口蘑', 'mushroom', 'mushrooms', 'button mushroom', 'white mushroom']::text[], 'gram', true, false, true, 3140, 'P0', 'mushroom', 'fridge', false, true),
  ('corn', '玉米', 'Corn', 'vegetable', array['玉米', '玉米粒', '甜玉米', 'corn', 'corn kernels', 'sweet corn']::text[], 'gram', true, false, true, 3150, 'P0', 'starchy_vegetable', 'fridge', false, true),
  ('green_beans', '四季豆', 'Green Beans', 'vegetable', array['四季豆', '豆角', '青豆角', 'green beans', 'green bean', 'string beans']::text[], 'gram', true, false, true, 3160, 'P0', 'beans_peas', 'fridge', false, true),
  ('cilantro', '香菜', 'Cilantro', 'vegetable', array['香菜', '芫荽', 'cilantro', 'coriander', 'fresh cilantro']::text[], 'gram', true, false, true, 3170, 'P1', 'herb', 'fridge', false, true),
  ('parsley', '欧芹', 'Parsley', 'vegetable', array['欧芹', 'parsley']::text[], 'gram', true, false, true, 3180, 'P1', 'herb', 'fridge', false, true),
  ('basil', '罗勒', 'Basil', 'vegetable', array['罗勒', '九层塔', 'basil']::text[], 'gram', true, false, true, 3190, 'P1', 'herb', 'fridge', false, true),
  ('cherry_tomato', '樱桃番茄', 'Cherry Tomato', 'vegetable', array['樱桃番茄', '小番茄', '圣女果', 'cherry tomato']::text[], 'piece', true, false, true, 3200, 'P1', 'fruiting_vegetable', 'fridge', false, true),
  ('kale', '羽衣甘蓝', 'Kale', 'vegetable', array['羽衣甘蓝', 'kale']::text[], 'gram', true, false, true, 3210, 'P1', 'leafy_green', 'fridge', false, true),
  ('napa_cabbage', '大白菜', 'Napa Cabbage', 'vegetable', array['大白菜', '白菜', '娃娃菜', 'napa cabbage', 'chinese cabbage']::text[], 'gram', true, false, true, 3220, 'P1', 'leafy_green', 'fridge', false, true),
  ('bok_choy', '小白菜', 'Bok Choy', 'vegetable', array['小白菜', '青菜', '上海青', 'bok choy']::text[], 'gram', true, false, true, 3230, 'P1', 'leafy_green', 'fridge', false, true),
  ('bell_pepper', '彩椒', 'Bell Pepper', 'vegetable', array['彩椒', '甜椒', '青椒', '灯笼椒', 'bell pepper', 'bell peppers', 'sweet pepper', 'sweet peppers']::text[], 'piece', true, false, true, 3240, 'P1', 'fruiting_vegetable', 'fridge', false, true),
  ('zucchini', '西葫芦', 'Zucchini', 'vegetable', array['西葫芦', 'zucchini']::text[], 'piece', true, false, true, 3250, 'P1', 'fruiting_vegetable', 'fridge', false, true),
  ('eggplant', '茄子', 'Eggplant', 'vegetable', array['茄子', 'eggplant', 'aubergine']::text[], 'piece', true, false, true, 3260, 'P1', 'fruiting_vegetable', 'fridge', false, true),
  ('celery', '芹菜', 'Celery', 'vegetable', array['芹菜', '西芹', 'celery']::text[], 'gram', true, false, true, 3270, 'P1', 'stem_vegetable', 'fridge', false, true),
  ('peas', '豌豆', 'Peas', 'vegetable', array['豌豆', '青豆', 'peas']::text[], 'gram', true, false, true, 3280, 'P1', 'beans_peas', 'freezer', false, true),
  ('edamame', '毛豆', 'Edamame', 'vegetable', array['毛豆', 'edamame']::text[], 'gram', true, false, true, 3290, 'P1', 'beans_peas', 'freezer', false, true),
  ('bean_sprouts', '豆芽', 'Bean Sprouts', 'vegetable', array['豆芽', '绿豆芽', 'bean sprouts']::text[], 'gram', true, false, true, 3300, 'P1', 'sprout', 'fridge', false, true),
  ('avocado', '牛油果', 'Avocado', 'vegetable', array['牛油果', '鳄梨', 'avocado']::text[], 'piece', true, false, true, 3310, 'P1', 'fruiting_vegetable', 'room_temp', false, true),
  ('frozen_mixed_vegetables', '冷冻混合蔬菜', 'Frozen Mixed Vegetables', 'vegetable', array['冷冻混合蔬菜', '冷冻蔬菜', 'frozen mixed vegetables']::text[], 'gram', false, true, true, 3320, 'P1', 'frozen_vegetable', 'freezer', false, false),
  ('frozen_broccoli', '冷冻西兰花', 'Frozen Broccoli', 'vegetable', array['冷冻西兰花', 'frozen broccoli']::text[], 'gram', false, true, true, 3330, 'P1', 'frozen_vegetable', 'freezer', false, false),
  ('frozen_spinach', '冷冻菠菜', 'Frozen Spinach', 'vegetable', array['冷冻菠菜', 'frozen spinach']::text[], 'gram', false, true, true, 3340, 'P1', 'frozen_vegetable', 'freezer', false, false),
  ('frozen_corn', '冷冻玉米', 'Frozen Corn', 'vegetable', array['冷冻玉米', 'frozen corn']::text[], 'gram', false, true, true, 3350, 'P1', 'frozen_vegetable', 'freezer', false, false),
  ('frozen_peas', '冷冻豌豆', 'Frozen Peas', 'vegetable', array['冷冻豌豆', 'frozen peas']::text[], 'gram', false, true, true, 3360, 'P1', 'frozen_vegetable', 'freezer', false, false),
  ('canned_corn', '罐头玉米', 'Canned Corn', 'vegetable', array['罐头玉米', '玉米罐头', 'canned corn']::text[], 'gram', false, true, true, 3370, 'P1', 'canned_vegetable', 'canned', false, false),
  ('canned_tomato', '罐头番茄', 'Canned Tomato', 'vegetable', array['罐头番茄', '番茄罐头', 'canned tomato', 'canned tomatoes']::text[], 'gram', false, true, true, 3380, 'P1', 'canned_vegetable', 'canned', false, false),
  ('canned_mushroom', '罐头蘑菇', 'Canned Mushroom', 'vegetable', array['罐头蘑菇', '蘑菇罐头', 'canned mushroom']::text[], 'gram', false, true, true, 3390, 'P1', 'canned_vegetable', 'canned', false, false),
  ('okra', '秋葵', 'Okra', 'vegetable', array['秋葵', 'okra']::text[], 'gram', true, false, true, 3400, 'P2', 'fruiting_vegetable', 'fridge', false, true),
  ('asparagus', '芦笋', 'Asparagus', 'vegetable', array['芦笋', 'asparagus']::text[], 'gram', true, false, true, 3410, 'P2', 'stem_vegetable', 'fridge', false, true),
  ('brussels_sprouts', '抱子甘蓝', 'Brussels Sprouts', 'vegetable', array['抱子甘蓝', 'brussels sprouts']::text[], 'gram', true, false, true, 3420, 'P2', 'cruciferous', 'fridge', false, true),
  ('beetroot', '甜菜根', 'Beetroot', 'vegetable', array['甜菜根', '甜菜', 'beetroot', 'beet']::text[], 'piece', true, false, true, 3430, 'P2', 'root_vegetable', 'fridge', false, true),
  ('pumpkin', '南瓜', 'Pumpkin', 'vegetable', array['南瓜', 'pumpkin', 'squash']::text[], 'gram', true, false, true, 3440, 'P2', 'starchy_vegetable', 'room_temp', false, true),
  ('garlic_chives', '韭菜', 'Garlic Chives', 'vegetable', array['韭菜', 'garlic chives', 'chives']::text[], 'gram', true, false, true, 3450, 'P2', 'aromatics', 'fridge', false, true),
  ('garlic_sprouts', '蒜苗', 'Garlic Sprouts', 'vegetable', array['蒜苗', '蒜苔', 'garlic sprouts']::text[], 'gram', true, false, true, 3460, 'P2', 'aromatics', 'fridge', false, true),
  ('lotus_root', '莲藕', 'Lotus Root', 'vegetable', array['莲藕', '藕', 'lotus root']::text[], 'gram', true, false, true, 3470, 'P2', 'root_vegetable', 'fridge', false, true),
  ('winter_melon', '冬瓜', 'Winter Melon', 'vegetable', array['冬瓜', 'winter melon']::text[], 'gram', true, false, true, 3480, 'P2', 'melon_vegetable', 'fridge', false, true),
  ('bitter_melon', '苦瓜', 'Bitter Melon', 'vegetable', array['苦瓜', 'bitter melon']::text[], 'gram', true, false, true, 3490, 'P2', 'melon_vegetable', 'fridge', false, true),

  ('banana', '香蕉', 'Banana', 'fruit', array['香蕉', 'banana', 'bananas', 'ripe banana']::text[], 'piece', true, false, true, 4010, 'P0', 'fresh_fruit', 'room_temp', false, true),
  ('apple', '苹果', 'Apple', 'fruit', array['苹果', 'apple', 'apples', 'red apple', 'green apple']::text[], 'piece', true, false, true, 4020, 'P0', 'fresh_fruit', 'room_temp', false, true),
  ('orange', '橙子', 'Orange', 'fruit', array['橙子', '橙', '甜橙', 'orange', 'oranges', 'navel orange']::text[], 'piece', true, false, true, 4030, 'P0', 'fresh_fruit', 'room_temp', false, true),
  ('lemon', '柠檬', 'Lemon', 'fruit', array['柠檬', 'lemon']::text[], 'piece', true, false, true, 4040, 'P1', 'citrus', 'fridge', false, true),
  ('lime', '酸橙', 'Lime', 'fruit', array['酸橙', '青柠', 'lime']::text[], 'piece', true, false, true, 4050, 'P1', 'citrus', 'fridge', false, true),
  ('grapes', '葡萄', 'Grapes', 'fruit', array['葡萄', 'grapes']::text[], 'gram', true, false, true, 4060, 'P1', 'fresh_fruit', 'fridge', false, true),
  ('strawberry', '草莓', 'Strawberry', 'fruit', array['草莓', 'strawberry', 'strawberries']::text[], 'gram', true, false, true, 4070, 'P1', 'berries', 'fridge', false, true),
  ('blueberry', '蓝莓', 'Blueberry', 'fruit', array['蓝莓', 'blueberry', 'blueberries']::text[], 'gram', true, false, true, 4080, 'P1', 'berries', 'fridge', false, true),
  ('berries', '浆果混合', 'Mixed Berries', 'fruit', array['浆果混合', '混合浆果', 'berries', 'mixed berries']::text[], 'gram', true, false, true, 4090, 'P1', 'berries', 'fridge', false, true),
  ('mango', '芒果', 'Mango', 'fruit', array['芒果', 'mango']::text[], 'piece', true, false, true, 4100, 'P1', 'tropical_fruit', 'room_temp', false, true),
  ('pineapple', '菠萝', 'Pineapple', 'fruit', array['菠萝', '凤梨', 'pineapple']::text[], 'gram', true, false, true, 4110, 'P1', 'tropical_fruit', 'fridge', false, true),
  ('pear', '梨', 'Pear', 'fruit', array['梨', 'pear']::text[], 'piece', true, false, true, 4120, 'P1', 'fresh_fruit', 'room_temp', false, true),
  ('peach', '桃子', 'Peach', 'fruit', array['桃子', '水蜜桃', 'peach']::text[], 'piece', true, false, true, 4130, 'P1', 'fresh_fruit', 'room_temp', false, true),
  ('frozen_berries', '冷冻浆果', 'Frozen Berries', 'fruit', array['冷冻浆果', 'frozen berries']::text[], 'gram', false, true, true, 4140, 'P1', 'frozen_fruit', 'freezer', false, false),
  ('frozen_mango', '冷冻芒果', 'Frozen Mango', 'fruit', array['冷冻芒果', 'frozen mango']::text[], 'gram', false, true, true, 4150, 'P1', 'frozen_fruit', 'freezer', false, false),
  ('canned_pineapple', '罐头菠萝', 'Canned Pineapple', 'fruit', array['罐头菠萝', '菠萝罐头', 'canned pineapple']::text[], 'gram', false, true, true, 4160, 'P1', 'canned_fruit', 'canned', false, false),
  ('canned_peach', '罐头桃子', 'Canned Peach', 'fruit', array['罐头桃子', '桃子罐头', 'canned peach']::text[], 'gram', false, true, true, 4170, 'P1', 'canned_fruit', 'canned', false, false),
  ('raisins', '葡萄干', 'Raisins', 'fruit', array['葡萄干', 'raisins']::text[], 'gram', false, true, true, 4180, 'P1', 'dried_fruit', 'pantry', false, false),
  ('dried_fruit', '果干混合', 'Dried Fruit', 'fruit', array['果干混合', '果干', 'dried fruit']::text[], 'gram', false, true, true, 4190, 'P1', 'dried_fruit', 'pantry', false, false),
  ('peanut_butter', '花生酱', 'Peanut Butter', 'pantry', array['花生酱', 'peanut butter']::text[], 'tbsp', false, true, true, 4200, 'P1', 'spread', 'pantry', false, false),
  ('jam', '果酱', 'Jam', 'sweetener', array['果酱', 'jam', 'fruit jam']::text[], 'tbsp', false, true, true, 4210, 'P1', 'spread', 'pantry', false, false),
  ('mixed_nuts', '坚果混合', 'Mixed Nuts', 'pantry', array['坚果混合', '混合坚果', 'mixed nuts']::text[], 'gram', false, true, true, 4220, 'P1', 'snack', 'pantry', false, false),
  ('granola', '格兰诺拉麦片', 'Granola', 'grain', array['格兰诺拉麦片', 'granola']::text[], 'cup', false, true, true, 4230, 'P1', 'snack', 'pantry', false, false),

  ('salt', '盐', 'Salt', 'seasoning', array['盐', '食盐', 'salt']::text[], 'pinch', false, true, true, 5010, 'P0', 'basic_seasoning', 'pantry', true, false),
  ('black_pepper', '黑胡椒', 'Black Pepper', 'seasoning', array['黑胡椒', '黑胡椒粉', '胡椒粉', 'pepper', 'black pepper', 'ground black pepper', 'cracked black pepper']::text[], 'pinch', false, true, true, 5020, 'P0', 'basic_seasoning', 'pantry', false, false),
  ('white_pepper', '白胡椒', 'White Pepper', 'seasoning', array['白胡椒', '白胡椒粉', 'white pepper']::text[], 'pinch', false, true, true, 5030, 'P0', 'basic_seasoning', 'pantry', false, false),
  ('sugar', '糖', 'Sugar', 'sweetener', array['糖', '白糖', 'sugar']::text[], 'tsp', false, true, true, 5040, 'P0', 'basic_seasoning', 'pantry', true, false),
  ('honey', '蜂蜜', 'Honey', 'sweetener', array['蜂蜜', 'honey']::text[], 'tbsp', false, true, true, 5050, 'P0', 'basic_seasoning', 'pantry', false, false),
  ('cooking_oil', '烹饪油', 'Cooking Oil', 'pantry', array['烹饪油', '食用油', '植物油', 'cooking oil']::text[], 'tbsp', false, true, true, 5060, 'P0', 'oil', 'pantry', false, false),
  ('olive_oil', '橄榄油', 'Olive Oil', 'pantry', array['橄榄油', 'olive oil']::text[], 'tbsp', false, true, true, 5070, 'P0', 'oil', 'pantry', false, false),
  ('butter', '黄油', 'Butter', 'dairy', array['黄油', 'butter']::text[], 'tbsp', false, true, true, 5080, 'P0', 'dairy_fat', 'fridge', false, true),
  ('soy_sauce', '酱油', 'Soy Sauce', 'sauce', array['酱油', '普通酱油', '黄豆酱油', 'soy sauce', 'soy sauces', 'regular soy sauce', 'all purpose soy sauce']::text[], 'tbsp', false, true, true, 5090, 'P0', 'asian_sauce', 'pantry', false, false),
  ('light_soy_sauce', '生抽', 'Light Soy Sauce', 'sauce', array['生抽', '淡酱油', 'light soy sauce']::text[], 'tbsp', false, true, true, 5100, 'P0', 'asian_sauce', 'pantry', false, false),
  ('dark_soy_sauce', '老抽', 'Dark Soy Sauce', 'sauce', array['老抽', 'dark soy sauce']::text[], 'tbsp', false, true, true, 5110, 'P0', 'asian_sauce', 'pantry', false, false),
  ('rice_vinegar', '米醋', 'Rice Vinegar', 'sauce', array['米醋', 'rice vinegar']::text[], 'tbsp', false, true, true, 5120, 'P0', 'vinegar', 'pantry', false, false),
  ('vinegar', '醋', 'Vinegar', 'sauce', array['醋', '白醋', '食醋', 'vinegar', 'white vinegar', 'distilled vinegar']::text[], 'tbsp', false, true, true, 5130, 'P0', 'vinegar', 'pantry', false, false),
  ('black_vinegar', '香醋', 'Black Vinegar', 'sauce', array['香醋', '镇江香醋', 'black vinegar']::text[], 'tbsp', false, true, true, 5140, 'P0', 'vinegar', 'pantry', false, false),
  ('sesame_oil', '芝麻油', 'Sesame Oil', 'pantry', array['芝麻油', '香油', '麻油', 'sesame oil', 'toasted sesame oil']::text[], 'tsp', false, true, true, 5150, 'P0', 'oil', 'pantry', false, false),
  ('oyster_sauce', '蚝油', 'Oyster Sauce', 'sauce', array['蚝油', '耗油', '蠔油', 'oyster sauce', 'oyster flavored sauce']::text[], 'tbsp', false, true, true, 5160, 'P0', 'asian_sauce', 'pantry', false, false),
  ('cooking_wine', '料酒', 'Cooking Wine', 'sauce', array['料酒', '绍兴料酒', '绍兴酒', 'cooking wine', 'shaoxing wine', 'rice cooking wine']::text[], 'tbsp', false, true, true, 5170, 'P0', 'asian_sauce', 'pantry', false, false),
  ('chili_oil', '辣椒油', 'Chili Oil', 'pantry', array['辣椒油', '红油', '辣油', 'chili oil', 'chilli oil', 'hot chili oil']::text[], 'tbsp', false, true, true, 5180, 'P1', 'asian_sauce', 'pantry', false, false),
  ('hot_sauce', '辣酱', 'Hot Sauce', 'sauce', array['辣酱', 'hot sauce']::text[], 'tbsp', false, true, true, 5190, 'P1', 'asian_sauce', 'pantry', false, false),
  ('chili_garlic_sauce', '蒜蓉辣酱', 'Chili Garlic Sauce', 'sauce', array['蒜蓉辣酱', 'chili garlic sauce']::text[], 'tbsp', false, true, true, 5200, 'P1', 'asian_sauce', 'pantry', false, false),
  ('doubanjiang', '豆瓣酱', 'Doubanjiang', 'sauce', array['豆瓣酱', '郫县豆瓣', '郫县豆瓣酱', '红油豆瓣', 'doubanjiang', 'chili bean paste', 'pixian doubanjiang']::text[], 'tbsp', false, true, true, 5210, 'P1', 'asian_paste', 'pantry', false, false),
  ('sweet_bean_sauce', '甜面酱', 'Sweet Bean Sauce', 'sauce', array['甜面酱', 'sweet bean sauce']::text[], 'tbsp', false, true, true, 5220, 'P1', 'asian_paste', 'pantry', false, false),
  ('hoisin_sauce', '海鲜酱', 'Hoisin Sauce', 'sauce', array['海鲜酱', '海鮮醬', 'hoisin sauce', 'chinese barbecue sauce']::text[], 'tbsp', false, true, true, 5230, 'P1', 'asian_sauce', 'pantry', false, false),
  ('miso', '味噌', 'Miso', 'sauce', array['味噌', '味增', '日式味噌', 'miso', 'miso paste', 'white miso', 'red miso']::text[], 'tbsp', false, true, true, 5240, 'P1', 'asian_paste', 'fridge', false, true),
  ('gochujang', '韩式辣酱', 'Gochujang', 'sauce', array['韩式辣酱', '韩国辣酱', '韩式甜辣酱', 'gochujang', 'korean chili paste', 'korean red pepper paste']::text[], 'tbsp', false, true, true, 5250, 'P1', 'asian_paste', 'fridge', false, true),
  ('teriyaki_sauce', '照烧酱', 'Teriyaki Sauce', 'sauce', array['照烧酱', 'teriyaki sauce']::text[], 'tbsp', false, true, true, 5260, 'P1', 'asian_sauce', 'pantry', false, false),
  ('fish_sauce', '鱼露', 'Fish Sauce', 'sauce', array['鱼露', 'fish sauce']::text[], 'tbsp', false, true, true, 5270, 'P1', 'asian_sauce', 'pantry', false, false),
  ('curry_blocks', '咖喱块', 'Curry Blocks', 'pantry', array['咖喱块', '日式咖喱块', '咖喱砖', 'curry blocks', 'curry block', 'curry roux', 'japanese curry roux']::text[], 'piece', false, true, true, 5280, 'P1', 'asian_paste', 'pantry', false, false),
  ('ketchup', '番茄酱', 'Ketchup', 'sauce', array['番茄酱', '蕃茄酱', 'ketchup', 'tomato ketchup', 'catsup']::text[], 'tbsp', false, true, true, 5290, 'P1', 'western_sauce', 'fridge', false, true),
  ('mayonnaise', '蛋黄酱', 'Mayonnaise', 'sauce', array['蛋黄酱', '美乃滋', '沙拉蛋黄酱', 'mayonnaise', 'mayo']::text[], 'tbsp', false, true, true, 5300, 'P1', 'western_sauce', 'fridge', false, true),
  ('mustard', '芥末', 'Mustard', 'sauce', array['芥末', '芥末酱', '黄芥末酱', 'mustard', 'mustard sauce', 'prepared mustard']::text[], 'tsp', false, true, true, 5310, 'P1', 'western_sauce', 'fridge', false, true),
  ('yellow_mustard', '黄芥末', 'Yellow Mustard', 'sauce', array['黄芥末', 'yellow mustard']::text[], 'tsp', false, true, true, 5320, 'P1', 'western_sauce', 'fridge', false, true),
  ('dijon_mustard', '第戎芥末', 'Dijon Mustard', 'sauce', array['第戎芥末', 'dijon mustard']::text[], 'tsp', false, true, true, 5330, 'P1', 'western_sauce', 'fridge', false, true),
  ('sriracha', '辣椒酱', 'Sriracha', 'sauce', array['辣椒酱', '是拉差', '是拉差辣酱', 'sriracha', 'sriracha sauce']::text[], 'tbsp', false, true, true, 5340, 'P1', 'western_sauce', 'pantry', false, false),
  ('bbq_sauce', '烧烤酱', 'BBQ Sauce', 'sauce', array['烧烤酱', 'bbq sauce', 'barbecue sauce']::text[], 'tbsp', false, true, true, 5350, 'P1', 'western_sauce', 'fridge', false, true),
  ('salad_dressing', '沙拉酱', 'Salad Dressing', 'sauce', array['沙拉酱', 'salad dressing']::text[], 'tbsp', false, true, true, 5360, 'P1', 'western_sauce', 'fridge', false, true),
  ('pasta_sauce', '意面酱', 'Pasta Sauce', 'sauce', array['意面酱', '意大利面酱', '番茄意面酱', 'pasta sauce', 'marinara', 'marinara sauce', 'tomato pasta sauce']::text[], 'cup', false, true, true, 5370, 'P1', 'western_sauce', 'pantry', false, false),
  ('tomato_paste', '番茄膏', 'Tomato Paste', 'sauce', array['番茄膏', '番茄酱膏', 'tomato paste', 'canned tomato paste']::text[], 'tbsp', false, true, true, 5380, 'P1', 'western_sauce', 'canned', false, false),
  ('crushed_tomatoes', '罐头番茄碎', 'Crushed Tomatoes', 'sauce', array['罐头番茄碎', '番茄碎罐头', 'crushed tomatoes']::text[], 'cup', false, true, true, 5390, 'P1', 'western_sauce', 'canned', false, false),
  ('coconut_milk', '椰奶', 'Coconut Milk', 'pantry', array['椰奶', '椰浆', '椰子奶', 'coconut milk', 'canned coconut milk']::text[], 'ml', false, true, true, 5400, 'P1', 'canned_pantry', 'canned', false, false),
  ('cream', '奶油', 'Cream', 'dairy', array['奶油', '淡奶油', '鲜奶油', 'cream', 'heavy cream', 'whipping cream']::text[], 'ml', true, false, true, 5410, 'P1', 'dairy', 'fridge', false, true),
  ('sour_cream', '酸奶油', 'Sour Cream', 'dairy', array['酸奶油', '酸忌廉', 'sour cream']::text[], 'tbsp', true, false, true, 5420, 'P1', 'dairy', 'fridge', false, true),
  ('milk', '牛奶', 'Milk', 'dairy', array['牛奶', '鲜奶', '全脂牛奶', 'milk', 'whole milk', '2% milk', 'skim milk']::text[], 'ml', true, false, true, 5421, 'P0', 'dairy', 'fridge', false, true),
  ('yogurt', '酸奶', 'Yogurt', 'dairy', array['酸奶', '优格', '原味酸奶', 'yogurt', 'plain yogurt', 'greek yogurt']::text[], 'gram', true, false, true, 5422, 'P1', 'dairy', 'fridge', false, true),
  ('cheese', '奶酪', 'Cheese', 'dairy', array['奶酪', '芝士', '起司', 'cheese', 'cheddar cheese', 'mozzarella']::text[], 'gram', true, false, true, 5423, 'P1', 'dairy', 'fridge', false, true),
  ('garlic_powder', '蒜粉', 'Garlic Powder', 'seasoning', array['蒜粉', 'garlic powder']::text[], 'tsp', false, true, true, 5430, 'P1', 'spice', 'pantry', false, false),
  ('onion_powder', '洋葱粉', 'Onion Powder', 'seasoning', array['洋葱粉', 'onion powder']::text[], 'tsp', false, true, true, 5440, 'P1', 'spice', 'pantry', false, false),
  ('paprika', '辣椒粉', 'Paprika', 'seasoning', array['辣椒粉', '红椒粉', 'paprika']::text[], 'tsp', false, true, true, 5450, 'P1', 'spice', 'pantry', false, false),
  ('chili_flakes', '辣椒碎', 'Chili Flakes', 'seasoning', array['辣椒碎', '干辣椒碎', 'chili flakes']::text[], 'tsp', false, true, true, 5460, 'P1', 'spice', 'pantry', false, false),
  ('cumin', '孜然', 'Cumin', 'seasoning', array['孜然', '孜然粉', 'cumin']::text[], 'tsp', false, true, true, 5470, 'P1', 'spice', 'pantry', false, false),
  ('curry_powder', '咖喱粉', 'Curry Powder', 'seasoning', array['咖喱粉', 'curry powder']::text[], 'tsp', false, true, true, 5480, 'P1', 'spice', 'pantry', false, false),
  ('five_spice_powder', '五香粉', 'Five Spice Powder', 'seasoning', array['五香粉', 'five spice powder']::text[], 'tsp', false, true, true, 5490, 'P1', 'spice', 'pantry', false, false),
  ('sichuan_peppercorn_powder', '花椒粉', 'Sichuan Peppercorn Powder', 'seasoning', array['花椒粉', '花椒面', 'sichuan peppercorn powder']::text[], 'tsp', false, true, true, 5500, 'P1', 'spice', 'pantry', false, false),
  ('italian_seasoning', '意大利综合香草', 'Italian Seasoning', 'seasoning', array['意大利综合香草', '意式香草', 'italian seasoning']::text[], 'tsp', false, true, true, 5510, 'P1', 'herb_dried', 'pantry', false, false),
  ('oregano', '牛至', 'Oregano', 'seasoning', array['牛至', 'oregano']::text[], 'tsp', false, true, true, 5520, 'P1', 'herb_dried', 'pantry', false, false),
  ('thyme', '百里香', 'Thyme', 'seasoning', array['百里香', 'thyme']::text[], 'tsp', false, true, true, 5530, 'P1', 'herb_dried', 'pantry', false, false),
  ('rosemary', '迷迭香', 'Rosemary', 'seasoning', array['迷迭香', 'rosemary']::text[], 'tsp', false, true, true, 5540, 'P1', 'herb_dried', 'pantry', false, false),
  ('cinnamon', '肉桂粉', 'Cinnamon', 'seasoning', array['肉桂粉', 'cinnamon']::text[], 'tsp', false, true, true, 5550, 'P1', 'spice', 'pantry', false, false),
  ('bay_leaf', '月桂叶', 'Bay Leaf', 'seasoning', array['月桂叶', '香叶', 'bay leaf']::text[], 'piece', false, true, true, 5560, 'P1', 'herb_dried', 'pantry', false, false),
  ('cornstarch', '玉米淀粉', 'Cornstarch', 'pantry', array['玉米淀粉', '淀粉', '生粉', 'cornstarch', 'corn starch', 'corn flour']::text[], 'tbsp', false, true, true, 5570, 'P1', 'baking_helper', 'pantry', false, false),
  ('breadcrumbs', '面包糠', 'Breadcrumbs', 'pantry', array['面包糠', '面包屑', 'breadcrumbs']::text[], 'cup', false, true, true, 5580, 'P1', 'baking_helper', 'pantry', false, false),
  ('baking_powder', '泡打粉', 'Baking Powder', 'pantry', array['泡打粉', 'baking powder']::text[], 'tsp', false, true, true, 5590, 'P1', 'baking_helper', 'pantry', false, false),
  ('baking_soda', '小苏打', 'Baking Soda', 'pantry', array['小苏打', 'baking soda']::text[], 'tsp', false, true, true, 5600, 'P1', 'baking_helper', 'pantry', false, false),
  ('yeast', '酵母', 'Yeast', 'pantry', array['酵母', '干酵母', 'yeast']::text[], 'tsp', false, true, true, 5610, 'P1', 'baking_helper', 'pantry', false, false),
  ('stock_cube', '高汤块', 'Stock Cube', 'pantry', array['高汤块', '浓汤宝', 'stock cube', 'bouillon cube']::text[], 'piece', false, true, true, 5620, 'P1', 'broth', 'pantry', false, false),
  ('chicken_broth', '鸡汤', 'Chicken Broth', 'pantry', array['鸡汤', '鸡高汤', 'chicken broth', 'chicken stock']::text[], 'ml', false, true, true, 5630, 'P1', 'broth', 'pantry', false, false),
  ('vegetable_broth', '蔬菜汤', 'Vegetable Broth', 'pantry', array['蔬菜汤', '蔬菜高汤', 'vegetable broth']::text[], 'ml', false, true, true, 5640, 'P1', 'broth', 'pantry', false, false),
  ('beef_broth', '牛肉汤', 'Beef Broth', 'pantry', array['牛肉汤', '牛肉高汤', 'beef broth']::text[], 'ml', false, true, true, 5650, 'P1', 'broth', 'pantry', false, false),
  ('canned_chickpeas', '罐头鹰嘴豆', 'Canned Chickpeas', 'pantry', array['罐头鹰嘴豆', '鹰嘴豆罐头', 'canned chickpeas']::text[], 'gram', false, true, true, 5660, 'P1', 'canned_beans', 'canned', false, false),
  ('canned_black_beans', '罐头黑豆', 'Canned Black Beans', 'pantry', array['罐头黑豆', '黑豆罐头', 'canned black beans']::text[], 'gram', false, true, true, 5670, 'P1', 'canned_beans', 'canned', false, false),
  ('canned_kidney_beans', '罐头红腰豆', 'Canned Kidney Beans', 'pantry', array['罐头红腰豆', '红腰豆罐头', 'canned kidney beans']::text[], 'gram', false, true, true, 5680, 'P1', 'canned_beans', 'canned', false, false)
on conflict (ingredient_key) do update set
  zh_name = excluded.zh_name,
  en_name = excluded.en_name,
  category_key = excluded.category_key,
  aliases = excluded.aliases,
  default_unit_key = excluded.default_unit_key,
  is_fresh = excluded.is_fresh,
  is_pantry_item = excluded.is_pantry_item,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order,
  content_tier = excluded.content_tier,
  subcategory_key = excluded.subcategory_key,
  storage_type = excluded.storage_type,
  is_basic_pantry = excluded.is_basic_pantry,
  is_fridge_recognition_target = excluded.is_fridge_recognition_target,
  updated_at = now();
